### ISSUE TITLE
installation on mac OSX

### ISSUE THREAD

**Issue by 2ge** [SigwoTechnologies/jupiter#12]
```
using Jupiter v1.13.1

$ uname -a
Darwin MacBook-Pro.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
$ java --version
java 14.0.2 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

log:
2020-08-06 13:08:36 INFO: nxt.enableStackTraces = "true"
2020-08-06 13:08:36 INFO: nxt.enableLogTraceback = "false"
2020-08-06 13:08:36 INFO: logging enabled
2020-08-06 13:08:36 INFO: socksProxyHost not defined
2020-08-06 13:08:36 INFO: socksProxyPort not defined
2020-08-06 13:08:36 FINE: java.version = 14.0.2
2020-08-06 13:08:36 FINE: java.vm.version = 14.0.2+12-46
2020-08-06 13:08:36 FINE: java.vm.name = Java HotSpot(TM) 64-Bit Server VM
2020-08-06 13:08:36 FINE: java.vendor = Oracle Corporation
2020-08-06 13:08:36 FINE: java.vm.vendor = Oracle Corporation
2020-08-06 13:08:36 FINE: java.home = /Library/Java/JavaVirtualMachines/jdk-14.0.2.jdk/Contents/Home
2020-08-06 13:08:36 FINE: java.library.path = /Users/brano/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
2020-08-06 13:08:36 FINE: java.class.path = classes:lib/bcprov-jdk15on-156.jar:lib/jetty-http-9.3.16.v20170120.jar:lib/jetty-proxy-9.3.16.v20170120.jar:lib/h2-1.4.194.jar:lib/slf4j-api-1.7.22.jar:lib/jetty-client-9.3.16.v20170120.jar:lib/lucene-core-5.3.2.jar:lib/tika-core-1.13.jar:lib/jetty-security-9.3.16.v20170120.jar:lib/slf4j-jdk14-1.7.22.jar:lib/websocket-server-9.3.16.v20170120.jar:lib/jetty-servlet-9.3.16.v20170120.jar:lib/javax.servlet-api-3.1.0.jar:lib/jetty-io-9.3.16.v20170120.jar:lib/javase-3.3.0.jar:lib/json-simple-1.1.1.jar:lib/websocket-client-9.3.16.v20170120.jar:lib/lucene-queryparser-5.3.2.jar:lib/jetty-servlets-9.3.16.v20170120.jar:lib/websocket-common-9.3.16.v20170120.jar:lib/jetty-server-9.3.16.v20170120.jar:lib/jetty-util-9.3.16.v20170120.jar:lib/lucene-analyzers-common-5.3.2.jar:lib/tika-parsers-1.13.jar:lib/jetty-continuation-9.3.16.v20170120.jar:lib/lucene-queries-5.3.2.jar:lib/core-3.3.0.jar:lib/websocket-servlet-9.3.16.v20170120.jar:lib/weupnp-0.1.4.jar:lib/websocket-api-9.3.16.v20170120.jar:conf:addons/classes:addons/lib/*
2020-08-06 13:08:36 FINE: os.arch = x86_64
2020-08-06 13:08:36 FINE: sun.arch.data.model = 64
2020-08-06 13:08:36 FINE: os.name = Mac OS X
2020-08-06 13:08:36 FINE: file.encoding = UTF-8
2020-08-06 13:08:36 FINE: java.security.policy = null
2020-08-06 13:08:36 FINE: java.security.manager = null
2020-08-06 13:08:36 FINE: nxt.runtime.mode = desktop
2020-08-06 13:08:36 FINE: nxt.runtime.dirProvider = null
2020-08-06 13:08:36 FINE: availableProcessors = 8
2020-08-06 13:08:36 FINE: maxMemory = 4294967296
2020-08-06 13:08:36 FINE: processId = 66117
2020-08-06 13:08:38 INFO: nxt.isTestnet = "false"
2020-08-06 13:08:38 INFO: nxt.isOffline = "false"
2020-08-06 13:08:38 INFO: nxt.isLightClient = "false"
2020-08-06 13:08:38 INFO: nxt.maxRollback = "800"
2020-08-06 13:08:38 INFO: nxt.forgingDelay = "20"
2020-08-06 13:08:38 INFO: nxt.forgingSpeedup = "3"
2020-08-06 13:08:38 INFO: nxt.maxPrunableLifetime = "-1"
2020-08-06 13:08:38 INFO: nxt.includeExpiredPrunable = "true"
2020-08-06 13:08:38 INFO: nxt.correctInvalidFees = "false"
2020-08-06 13:08:38 INFO: nxt.statementLogThreshold = "10000"
2020-08-06 13:08:38 INFO: nxt.transactionLogThreshold = "15000"
2020-08-06 13:08:38 INFO: nxt.transactionLogInterval = "15"
2020-08-06 13:08:38 INFO: nxt.dbCacheKB = "0"
2020-08-06 13:08:38 INFO: nxt.dbUrl not defined
2020-08-06 13:08:38 INFO: nxt.dbType = "h2"
2020-08-06 13:08:38 INFO: nxt.dbDir = "./nxt_db/nxt"
2020-08-06 13:08:38 INFO: nxt.dbParams = "DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE;MV_STORE=FALSE"
2020-08-06 13:08:38 INFO: nxt.dbUsername = "sa"
2020-08-06 13:08:38 INFO: nxt.dbPassword = "{not logged}"
2020-08-06 13:08:38 INFO: nxt.maxDbConnections = "30"
2020-08-06 13:08:38 INFO: nxt.dbLoginTimeout = "70"
2020-08-06 13:08:38 INFO: nxt.dbDefaultLockTimeout = "60"
2020-08-06 13:08:38 INFO: nxt.dbMaxMemoryRows = "1000000"
2020-08-06 13:08:38 FINE: Database jdbc url set to jdbc:h2:/Users/brano/.jrs/./nxt_db/nxt;DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE;MV_STORE=FALSE;CACHE_SIZE=262144 username sa
2020-08-06 13:08:39 INFO: nxt.useStrongSecureRandom = "false"
2020-08-06 13:08:41 FINE: Database connection pool current size: 1
2020-08-06 13:08:41 INFO: Database update may take a while if needed, current db version 198...
2020-08-06 13:08:41 FINE: Database connection pool current size: 2
2020-08-06 13:08:41 INFO: Lucene search index deleted
2020-08-06 13:08:41 SEVERE: Unable to access the Lucene index
java.io.IOException: Unable to unmap the mapped buffer: MMapIndexInput(path="/Users/brano/.jrs/nxt_db/nxt/_0_Lucene50_0.doc")
	at org.apache.lucene.store.MMapDirectory$2.freeBuffer(MMapDirectory.java:329)
	at org.apache.lucene.store.ByteBufferIndexInput.freeBuffer(ByteBufferIndexInput.java:376)
	at org.apache.lucene.store.ByteBufferIndexInput.close(ByteBufferIndexInput.java:355)
	at org.apache.lucene.codecs.lucene50.Lucene50CompoundFormat.write(Lucene50CompoundFormat.java:92)
	at org.apache.lucene.index.IndexWriter.createCompoundFile(IndexWriter.java:4680)
	at org.apache.lucene.index.DocumentsWriterPerThread.sealFlushedSegment(DocumentsWriterPerThread.java:492)
	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:459)
	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:503)
	at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:615)
	at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:2813)
	at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:2977)
	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:2944)
	at nxt.db.FullTextTrigger.getIndexAccess(FullTextTrigger.java:866)
	at nxt.db.FullTextTrigger.removeIndexFiles(FullTextTrigger.java:935)
	at nxt.db.FullTextTrigger.init(FullTextTrigger.java:203)
	at nxt.NxtDbVersion.update(NxtDbVersion.java:546)
	at nxt.db.DbVersion.init(DbVersion.java:55)
	at nxt.db.BasicDb.init(BasicDb.java:149)
	at nxt.Db.init(Db.java:40)
	at nxt.Nxt$Init.<clinit>(Nxt.java:341)
	at nxt.Nxt.init(Nxt.java:311)
	at nxt.Nxt.main(Nxt.java:298)
Caused by: java.lang.IllegalAccessException: class org.apache.lucene.store.MMapDirectory$2$1 cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @418e7838
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:376)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:647)
	at java.base/java.lang.reflect.Method.invoke(Method.java:556)
	at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:322)
	at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:314)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.apache.lucene.store.MMapDirectory$2.freeBuffer(MMapDirectory.java:314)
	... 21 more
2020-08-06 13:08:41 SEVERE: Unable to initialize NRS fulltext search support
java.sql.SQLException: Unable to access the Lucene index
	at nxt.db.FullTextTrigger.getIndexAccess(FullTextTrigger.java:876)
	at nxt.db.FullTextTrigger.removeIndexFiles(FullTextTrigger.java:935)
	at nxt.db.FullTextTrigger.init(FullTextTrigger.java:203)
	at nxt.NxtDbVersion.update(NxtDbVersion.java:546)
	at nxt.db.DbVersion.init(DbVersion.java:55)
	at nxt.db.BasicDb.init(BasicDb.java:149)
	at nxt.Db.init(Db.java:40)
	at nxt.Nxt$Init.<clinit>(Nxt.java:341)
	at nxt.Nxt.init(Nxt.java:311)
	at nxt.Nxt.main(Nxt.java:298)
Caused by: java.io.IOException: Unable to unmap the mapped buffer: MMapIndexInput(path="/Users/brano/.jrs/nxt_db/nxt/_0_Lucene50_0.doc")
	at org.apache.lucene.store.MMapDirectory$2.freeBuffer(MMapDirectory.java:329)
	at org.apache.lucene.store.ByteBufferIndexInput.freeBuffer(ByteBufferIndexInput.java:376)
	at org.apache.lucene.store.ByteBufferIndexInput.close(ByteBufferIndexInput.java:355)
	at org.apache.lucene.codecs.lucene50.Lucene50CompoundFormat.write(Lucene50CompoundFormat.java:92)
	at org.apache.lucene.index.IndexWriter.createCompoundFile(IndexWriter.java:4680)
	at org.apache.lucene.index.DocumentsWriterPerThread.sealFlushedSegment(DocumentsWriterPerThread.java:492)
	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:459)
	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:503)
	at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:615)
	at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:2813)
	at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:2977)
	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:2944)
	at nxt.db.FullTextTrigger.getIndexAccess(FullTextTrigger.java:866)
	... 9 more
Caused by: java.lang.IllegalAccessException: class org.apache.lucene.store.MMapDirectory$2$1 cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @418e7838
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:376)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:647)
	at java.base/java.lang.reflect.Method.invoke(Method.java:556)
	at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:322)
	at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:314)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.apache.lucene.store.MMapDirectory$2.freeBuffer(MMapDirectory.java:314)
	... 21 more
2020-08-06 13:08:41 SEVERE: java.sql.SQLException: Unable to access the Lucene index
java.lang.RuntimeException: java.sql.SQLException: Unable to access the Lucene index
	at nxt.db.FullTextTrigger.init(FullTextTrigger.java:251)
	at nxt.NxtDbVersion.update(NxtDbVersion.java:546)
	at nxt.db.DbVersion.init(DbVersion.java:55)
	at nxt.db.BasicDb.init(BasicDb.java:149)
	at nxt.Db.init(Db.java:40)
	at nxt.Nxt$Init.<clinit>(Nxt.java:341)
	at nxt.Nxt.init(Nxt.java:311)
	at nxt.Nxt.main(Nxt.java:298)
Caused by: java.sql.SQLException: Unable to access the Lucene index
	at nxt.db.FullTextTrigger.getIndexAccess(FullTextTrigger.java:876)
	at nxt.db.FullTextTrigger.removeIndexFiles(FullTextTrigger.java:935)
	at nxt.db.FullTextTrigger.init(FullTextTrigger.java:203)
	... 7 more
Caused by: java.io.IOException: Unable to unmap the mapped buffer: MMapIndexInput(path="/Users/brano/.jrs/nxt_db/nxt/_0_Lucene50_0.doc")
	at org.apache.lucene.store.MMapDirectory$2.freeBuffer(MMapDirectory.java:329)
	at org.apache.lucene.store.ByteBufferIndexInput.freeBuffer(ByteBufferIndexInput.java:376)
	at org.apache.lucene.store.ByteBufferIndexInput.close(ByteBufferIndexInput.java:355)
	at org.apache.lucene.codecs.lucene50.Lucene50CompoundFormat.write(Lucene50CompoundFormat.java:92)
	at org.apache.lucene.index.IndexWriter.createCompoundFile(IndexWriter.java:4680)
	at org.apache.lucene.index.DocumentsWriterPerThread.sealFlushedSegment(DocumentsWriterPerThread.java:492)
	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:459)
	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:503)
	at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:615)
	at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:2813)
	at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:2977)
	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:2944)
	at nxt.db.FullTextTrigger.getIndexAccess(FullTextTrigger.java:866)
	... 9 more
Caused by: java.lang.IllegalAccessException: class org.apache.lucene.store.MMapDirectory$2$1 cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @418e7838
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:376)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:647)
	at java.base/java.lang.reflect.Method.invoke(Method.java:556)
	at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:322)
	at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:314)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.apache.lucene.store.MMapDirectory$2.freeBuffer(MMapDirectory.java:314)
	... 21 more
```

**Comment by sigwo** [comment]
Please verify Java version. You should be running Java 8.
