### ISSUE TITLE
Installation of Jupiter Wallet on Windows 10 Home 64-bit

### ISSUE THREAD

**Issue by Bshowtime** [SigwoTechnologies/jupiter#13]
Good Afternoon JUP,

I am having difficulty getting the Jupiter Wallet to open.  Would you please look at the Java 8 Build 261 file below and point me in the right direction?

Initializing JRS server version 1.13.1
Command line arguments
-Dnxt.runtime.mode=desktop
isHeadless=false
Runtime mode nxt.env.DesktopMode
User home folder C:\Users\SEPTA Track\AppData\Roaming\JRS
Loading nxt-default.properties from classpath
Loading nxt.properties from dir C:\Users\SEPTA Track\AppData\Roaming\JRS\conf
Loading logging-default.properties from classpath
Loading logging.properties from dir C:\Users\SEPTA Track\AppData\Roaming\JRS\conf
Logs dir C:\Users\SEPTA Track\AppData\Roaming\JRS\logs
2020-08-27 13:40:52 INFO: nxt.enableStackTraces = "true"
2020-08-27 13:40:52 INFO: nxt.enableLogTraceback = "false"
2020-08-27 13:40:52 INFO: logging enabled
2020-08-27 13:40:52 INFO: socksProxyHost not defined
2020-08-27 13:40:52 INFO: socksProxyPort not defined
2020-08-27 13:40:52 FINE: java.version = 1.8.0_261
2020-08-27 13:40:52 FINE: java.vm.version = 25.261-b12
2020-08-27 13:40:52 FINE: java.vm.name = Java HotSpot(TM) Client VM
2020-08-27 13:40:52 FINE: java.vendor = Oracle Corporation
2020-08-27 13:40:52 FINE: java.vm.vendor = Oracle Corporation
2020-08-27 13:40:52 FINE: java.home = C:\Program Files (x86)\Java\jre1.8.0_261
2020-08-27 13:40:52 FINE: java.library.path = C:\Program Files (x86)\Java\jre1.8.0_261\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Dell\DW WLAN Card;;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Users\SEPTA Track\AppData\Local\Microsoft\WindowsApps;;.
2020-08-27 13:40:52 FINE: java.class.path = classes;lib\bcprov-jdk15on-156.jar;lib\core-3.3.0.jar;lib\h2-1.4.194.jar;lib\javase-3.3.0.jar;lib\javax.servlet-api-3.1.0.jar;lib\jetty-client-9.3.16.v20170120.jar;lib\jetty-continuation-9.3.16.v20170120.jar;lib\jetty-http-9.3.16.v20170120.jar;lib\jetty-io-9.3.16.v20170120.jar;lib\jetty-proxy-9.3.16.v20170120.jar;lib\jetty-security-9.3.16.v20170120.jar;lib\jetty-server-9.3.16.v20170120.jar;lib\jetty-servlet-9.3.16.v20170120.jar;lib\jetty-servlets-9.3.16.v20170120.jar;lib\jetty-util-9.3.16.v20170120.jar;lib\json-simple-1.1.1.jar;lib\lucene-analyzers-common-5.3.2.jar;lib\lucene-core-5.3.2.jar;lib\lucene-queries-5.3.2.jar;lib\lucene-queryparser-5.3.2.jar;lib\slf4j-api-1.7.22.jar;lib\slf4j-jdk14-1.7.22.jar;lib\tika-core-1.13.jar;lib\tika-parsers-1.13.jar;lib\websocket-api-9.3.16.v20170120.jar;lib\websocket-client-9.3.16.v20170120.jar;lib\websocket-common-9.3.16.v20170120.jar;lib\websocket-server-9.3.16.v20170120.jar;lib\websocket-servlet-9.3.16.v20170120.jar;lib\weupnp-0.1.4.jar;conf;addons\classes;addons\lib\*
2020-08-27 13:40:52 FINE: os.arch = x86
2020-08-27 13:40:52 FINE: sun.arch.data.model = 32
2020-08-27 13:40:52 FINE: os.name = Windows 10
2020-08-27 13:40:52 FINE: file.encoding = Cp1252
2020-08-27 13:40:52 FINE: java.security.policy = null
2020-08-27 13:40:52 FINE: java.security.manager = null
2020-08-27 13:40:52 FINE: nxt.runtime.mode = desktop
2020-08-27 13:40:52 FINE: nxt.runtime.dirProvider = null
2020-08-27 13:40:52 FINE: availableProcessors = 4
2020-08-27 13:40:52 FINE: maxMemory = 259522560
2020-08-27 13:40:52 FINE: processId = 7612
2020-08-27 13:40:52 INFO: nxt.isTestnet = "false"
2020-08-27 13:40:52 INFO: nxt.isOffline = "false"
2020-08-27 13:40:52 INFO: nxt.isLightClient = "false"
2020-08-27 13:40:52 INFO: nxt.maxRollback = "800"
2020-08-27 13:40:52 INFO: nxt.launchDesktopApplication = "true"
2020-08-27 13:40:52 INFO: nxt.forgingDelay = "20"
2020-08-27 13:40:52 INFO: nxt.forgingSpeedup = "3"
2020-08-27 13:40:52 INFO: nxt.maxPrunableLifetime = "-1"
2020-08-27 13:40:52 INFO: nxt.includeExpiredPrunable = "true"
2020-08-27 13:40:52 INFO: nxt.correctInvalidFees = "false"
2020-08-27 13:40:52 INFO: nxt.statementLogThreshold = "10000"
2020-08-27 13:40:52 INFO: nxt.transactionLogThreshold = "15000"
2020-08-27 13:40:52 INFO: nxt.transactionLogInterval = "15"
2020-08-27 13:40:52 INFO: nxt.dbCacheKB = "0"
2020-08-27 13:40:52 INFO: nxt.dbUrl not defined
2020-08-27 13:40:52 INFO: nxt.dbType = "h2"
2020-08-27 13:40:52 INFO: nxt.dbDir = "./nxt_db/nxt"
2020-08-27 13:40:52 INFO: nxt.dbParams = "DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE;MV_STORE=FALSE"
2020-08-27 13:40:52 INFO: nxt.dbUsername = "sa"
2020-08-27 13:40:52 INFO: nxt.dbPassword = "{not logged}"
2020-08-27 13:40:52 INFO: nxt.maxDbConnections = "30"
2020-08-27 13:40:52 INFO: nxt.dbLoginTimeout = "70"
2020-08-27 13:40:52 INFO: nxt.dbDefaultLockTimeout = "60"
2020-08-27 13:40:52 INFO: nxt.dbMaxMemoryRows = "1000000"
2020-08-27 13:40:52 FINE: Database jdbc url set to jdbc:h2:C:\Users\SEPTA Track\AppData\Roaming\JRS\.\nxt_db\nxt;DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE;MV_STORE=FALSE;CACHE_SIZE=60416 username sa
2020-08-27 13:40:52 INFO: nxt.useStrongSecureRandom = "false"
2020-08-27 13:40:56 FINE: Database connection pool current size: 1
2020-08-27 13:40:56 INFO: Database update may take a while if needed, current db version 237...
2020-08-27 13:40:56 INFO: nxt.enableTransactionRebroadcasting = "true"
2020-08-27 13:40:56 INFO: nxt.testUnconfirmedTransactions not defined, assuming false
2020-08-27 13:40:56 INFO: nxt.maxUnconfirmedTransactions = "20000"
2020-08-27 13:40:56 INFO: nxt.trimDerivedTables = "true"
2020-08-27 13:40:56 INFO: nxt.numberOfForkConfirmations = "0"
2020-08-27 13:40:56 INFO: nxt.simulateEndlessDownload not defined, assuming false
2020-08-27 13:40:56 INFO: nxt.trimFrequency = "1000"
2020-08-27 13:40:56 INFO: nxt.disableGetMoreBlocksThread not defined, assuming false
2020-08-27 13:40:56 INFO: nxt.disableProcessTransactionsThread not defined, assuming false
2020-08-27 13:40:56 INFO: nxt.disableRebroadcastTransactionsThread not defined, assuming false
2020-08-27 13:40:56 INFO: nxt.disableRemoveUnconfirmedTransactionsThread not defined, assuming false
2020-08-27 13:40:56 INFO: nxt.disableProcessWaitingTransactionsThread not defined, assuming false
2020-08-27 13:40:56 INFO: nxt.enablePublicKeyCache = "true"
2020-08-27 13:40:56 INFO: nxt.ledgerTrimKeep = "30000"
2020-08-27 13:40:56 INFO: nxt.ledgerAccounts = "*"
2020-08-27 13:40:56 INFO: Account ledger is tracking all accounts
2020-08-27 13:40:56 INFO: nxt.ledgerLogUnconfirmed = "2"
2020-08-27 13:40:56 INFO: nxt.processPolls = "true"
2020-08-27 13:40:56 INFO: nxt.deleteFinishedShufflings = "false"
2020-08-27 13:40:56 INFO: nxt.hideErrorDetails = "false"
2020-08-27 13:40:56 INFO: nxt.myPlatform = "Generic Jupiter Node"
2020-08-27 13:40:56 INFO: nxt.myAddress not defined
2020-08-27 13:40:56 INFO: nxt.peerServerPort = "7864"
2020-08-27 13:40:56 INFO: nxt.shareMyAddress = "true"
2020-08-27 13:40:56 INFO: nxt.enablePeerUPnP = "true"
2020-08-27 13:40:56 INFO: nxt.myHallmark not defined
2020-08-27 13:40:56 INFO: nxt.adminPassword not defined
2020-08-27 13:40:56 INFO: nxt.maxAPIRecords = "1000"
2020-08-27 13:40:56 INFO: nxt.enableAPIUPnP = "false"
2020-08-27 13:40:56 INFO: nxt.apiServerIdleTimeout = "30000"
2020-08-27 13:40:56 INFO: nxt.apiServerCORS = "true"
2020-08-27 13:40:56 INFO: nxt.disabledAPIs not defined
2020-08-27 13:40:56 INFO: nxt.disabledAPITags not defined
2020-08-27 13:40:56 INFO: nxt.allowedBotHosts = "127.0.0.1; localhost; [0:0:0:0:0:0:0:1];*;"
2020-08-27 13:40:56 INFO: nxt.enableAPIServer = "true"
2020-08-27 13:40:56 INFO: nxt.apiServerPort = "7876"
2020-08-27 13:40:56 INFO: nxt.apiServerSSLPort = "7876"
2020-08-27 13:40:56 INFO: nxt.apiServerHost = "0.0.0.0"
2020-08-27 13:40:56 INFO: nxt.disableAdminPassword = "false"
2020-08-27 13:40:56 INFO: nxt.apiSSL = "false"
2020-08-27 13:40:56 INFO: API server using HTTP port 7876
2020-08-27 13:40:56 INFO: nxt.apiResourceBase = "./html/www"
2020-08-27 13:40:56 INFO: nxt.apiWelcomeFile = "index.html"
2020-08-27 13:40:56 INFO: nxt.javadocResourceBase = "./html/doc"
2020-08-27 13:40:56 INFO: nxt.maxUploadFileSize not defined or not numeric, using default value 0
2020-08-27 13:40:56 INFO: nxt.maxUploadFileSize not defined or not numeric, using default value 0
2020-08-27 13:40:57 INFO: nxt.enableAPIServerGZIPFilter = "false"
2020-08-27 13:40:57 INFO: nxt.apiFrameOptionsSameOrigin = "true"
2020-08-27 13:40:57 FINE: My peer info:
{"apiPort":7876,"application":"JRS","apiServerIdleTimeout":30000,"services":"22","version":"1.13.1","platform":"Generic Jupiter Node","disabledAPIs":"","shareAddress":true}
2020-08-27 13:40:57 INFO: nxt.defaultPeers not defined
2020-08-27 13:40:57 INFO: nxt.wellKnownPeers = "jpr.gojupiter.tech;jpr2.gojupiter.tech;jpr3.gojupiter.tech;jpr4.gojupiter.tech;"
2020-08-27 13:40:57 INFO: nxt.knownBlacklistedPeers = "jill.airdns.org:17874;50.225.198.67:6221;"
2020-08-27 13:40:57 INFO: nxt.maxNumberOfInboundConnections = "250"
2020-08-27 13:40:57 INFO: nxt.maxNumberOfOutboundConnections = "50"
2020-08-27 13:40:57 INFO: nxt.maxNumberOfConnectedPublicPeers = "200"
2020-08-27 13:40:57 INFO: nxt.maxNumberOfKnownPeers = "2000"
2020-08-27 13:40:57 INFO: nxt.minNumberOfKnownPeers = "1000"
2020-08-27 13:40:57 INFO: nxt.connectTimeout = "10000"
2020-08-27 13:40:57 INFO: nxt.readTimeout = "20000"
2020-08-27 13:40:57 INFO: nxt.enableHallmarkProtection = "true"
2020-08-27 13:40:57 INFO: nxt.pushThreshold = "0"
2020-08-27 13:40:57 INFO: nxt.pullThreshold = "0"
2020-08-27 13:40:57 INFO: nxt.useWebSockets = "true"
2020-08-27 13:40:57 INFO: nxt.webSocketIdleTimeout = "900000"
2020-08-27 13:40:57 INFO: nxt.enablePeerServerGZIPFilter = "true"
2020-08-27 13:40:57 INFO: nxt.blacklistingPeriod = "600000"
2020-08-27 13:40:57 INFO: nxt.communicationLoggingMask = "0"
2020-08-27 13:40:57 INFO: nxt.sendToPeersLimit = "2"
2020-08-27 13:40:57 INFO: nxt.usePeersDb = "false"
2020-08-27 13:40:57 INFO: nxt.getMorePeers = "true"
2020-08-27 13:40:57 INFO: nxt.cjdnsOnly = "false"
2020-08-27 13:40:57 INFO: nxt.ignorePeerAnnouncedAddress = "false"
2020-08-27 13:40:57 INFO: nxt.disablePeerConnectingThread not defined, assuming false
2020-08-27 13:40:57 INFO: nxt.disablePeerUnBlacklistingThread not defined, assuming false
2020-08-27 13:40:57 INFO: nxt.disableGetMorePeersThread not defined, assuming false
2020-08-27 13:40:57 INFO: nxt.peerServerHost = "0.0.0.0"
2020-08-27 13:40:57 INFO: nxt.peerServerIdleTimeout = "30000"
2020-08-27 13:40:57 INFO: nxt.enablePeerServerDoSFilter = "true"
2020-08-27 13:40:57 INFO: nxt.peerServerDoSFilter.maxRequestsPerSec = "30"
2020-08-27 13:40:57 INFO: nxt.peerServerDoSFilter.delayMs = "1000"
2020-08-27 13:40:57 INFO: nxt.peerServerDoSFilter.maxRequestMs = "300000"
2020-08-27 13:40:57 INFO: nxt.enableAPIProxy = "true"
2020-08-27 13:40:57 INFO: nxt.apiProxyBlacklistingPeriod = "1800000"
2020-08-27 13:40:57 INFO: nxt.forceAPIProxyServerURL not defined
2020-08-27 13:40:57 INFO: nxt.maxNumberOfForgers = "100"
2020-08-27 13:40:57 INFO: nxt.enableFakeForging not defined, assuming false
2020-08-27 13:40:57 INFO: nxt.disableGenerateBlocksThread not defined, assuming false
2020-08-27 13:40:57 INFO: nxt.addOns not defined
2020-08-27 13:40:57 INFO: nxt.debugTraceQuote = """
2020-08-27 13:40:57 INFO: nxt.debugTraceSeparator = "   "
2020-08-27 13:40:57 INFO: nxt.debugLogUnconfirmed = "false"
2020-08-27 13:40:57 INFO: nxt.debugTraceAccounts not defined
2020-08-27 13:40:57 INFO: nxt.debugTraceLog = "nxt-trace.csv"
2020-08-27 13:40:57 FINE: Running 2 tasks...
2020-08-27 13:40:57 INFO: Genesis block already in database
2020-08-27 13:40:57 FINE: Rollback from block 15453713085233850541 at height 1355501 to 15453713085233850541 at 1355501
2020-08-27 13:40:57 FINE: Average database transaction time is 0.109 seconds
2020-08-27 13:40:57 INFO: Last block height: 1355501
2020-08-27 13:40:57 INFO: nxt.forceScan = "false"
2020-08-27 13:40:57 FINE: Running 2 final tasks...
2020-08-27 13:40:57 INFO: Looking for UPnP gateway device...
2020-08-27 13:40:57 INFO: nxt.upnpGatewayTimeout not defined or not numeric, using default value 7000
2020-08-27 13:40:57 INFO: nxt.apiServerEnforcePOST = "true"
2020-08-27 13:40:57 INFO: nxt.upnpDiscoverTimeout not defined or not numeric, using default value 3000
2020-08-27 13:40:58 INFO: Started API server at 0.0.0.0:7876
2020-08-27 13:41:07 FINE: There are no UPnP gateway devices
2020-08-27 13:41:07 INFO: Started peer networking server at 0.0.0.0:7864
2020-08-27 13:41:07 FINE: Starting 9 background jobs
2020-08-27 13:41:07 FINE: Starting 2 delayed tasks
2020-08-27 13:41:07 FINE: Known peers: 4
2020-08-27 13:41:07 INFO: Initialization took 15 seconds
2020-08-27 13:41:07 INFO: JRS server 1.13.1 started successfully.
2020-08-27 13:41:07 INFO: Copyright ⌐ 2013-2016 The Nxt Core Developers.
2020-08-27 13:41:07 INFO: Copyright ⌐ 2016-2017 Jelurida IP B.V.
2020-08-27 13:41:07 INFO: Copyright ⌐ 2016-2020 Sigwo Technologies
2020-08-27 13:41:07 INFO: Distributed under GPLv2, with ABSOLUTELY NO WARRANTY.
2020-08-27 13:41:07 INFO: Client UI is at http://localhost:7876/index.html
2020-08-27 13:41:07 INFO: nxt.launchDesktopApplication = "true"
2020-08-27 13:41:07 INFO: Launching desktop wallet
2020-08-27 13:41:07 INFO: nxtdesktop.DesktopApplication failed to launch
java.lang.ClassNotFoundException: nxtdesktop.DesktopApplication
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at nxt.env.DesktopMode.launchDesktopApplication(DesktopMode.java:46)
        at nxt.Nxt.launchDesktopApplication(Nxt.java:523)
        at nxt.Nxt.access$700(Nxt.java:51)
        at nxt.Nxt$Init.<clinit>(Nxt.java:400)
        at nxt.Nxt.init(Nxt.java:311)
        at nxt.Nxt.main(Nxt.java:298)
2020-08-27 13:41:08 FINE: Database connection pool current size: 2

Thanks for you help!

**Comment by sigwo** [comment]
The desktop wallet didn't auto launch. Open a browser and type `http://127.0.0.1:7876`

**Comment by Bshowtime** [comment]
Thank you!!!
